{% set version = "0.0.1" %}

package:
  name: pypta
  version: {{ version }}

source:
  path: ./

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - pip
    - python=3.7
    - pybind11
    - setuptools
    - wheel
    - ninja
    - cmake=3.4
  run:
    - python>=3.7

test:
  imports:
    - pyPTA
