name: Testing cPTA

on:
  - push
  - pull_request

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: configure
        run: mkdir ./src/cpp/tests/build && cd ./src/cpp/tests/build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: make
        run: cd ./src/cpp/tests/build && make
