name: Testing cPTA

on:
  - push
  - pull_request

jobs:
  build:
      runs-on: ubuntu-20.04
      steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: build cPTA and tests
        working-directory: /home/runner/work/pyPTA/pyPTA/src/cpp/
        run: |
          mkdir build
          cd build && cmake ..
          cmake --build . --config Debug --target cPTATests -j 6 --
      - name: Run Tests
        working-directory: /home/runner/work/pyPTA/pyPTA/src/cpp/
        run: ./build/tests/cPTATests
