name: Build and Testing Workflow

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.7', '3.8', '3.9', '3.10.6']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel pybind11 cmake ninja mypy
    - name: Build and install pyPTA
      run: |
        python -m pip install -e . 
    - name: Install test dependencies
      run: python -m pip install pytest numpy
    - name: Check typings
      run: |
        python -m mypy tests --config-file ./pyproject.toml
        python -m mypy src/python --config-file ./pyproject.toml
    - name: Test with pytest
      run: pytest tests